server:
  port: 8081

spring:
  application:
    name: user-service
  
  profiles:
    active: prod
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: users
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.sandbox: DEBUG
