server:
  port: 8085

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4201"
              - "http://localhost:4202"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

auth:
  service:
    url: ${AUTH_SERVICE_PROD_URL:http://auth-service-prod:8083}

gateway:
  environment: sandbox

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
