server:
  port: 8088

spring:
  application:
    name: cashin-service
  
  profiles:
    active: prod
  
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox_prod
    username: ${POSTGRES_USER:sandbox_user}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_schema: virtual_accounts
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.sandbox: DEBUG
